### ISSUE TITLE
String index out of range: -5

### ISSUE THREAD

**Issue by mnleano** [pedrovgs/AndroidWiFiADB#28]
String index out of range: -5
java.lang.StringIndexOutOfBoundsException: String index out of range: -5
    at java.lang.String.substring(String.java:1937)
    at com.github.pedrovgs.androidwifiadb.adb.ADBParser.parseGetDeviceIp(ADBParser.java:71)
    at com.github.pedrovgs.androidwifiadb.adb.ADB.getDeviceIp(ADB.java:68)
    at com.github.pedrovgs.androidwifiadb.adb.ADB.connectDeviceByIp(ADB.java:56)
    at com.github.pedrovgs.androidwifiadb.adb.ADB.connectDevices(ADB.java:49)
    at com.github.pedrovgs.androidwifiadb.AndroidWiFiADB.connectDevices(AndroidWiFiADB.java:45)
    at com.github.pedrovgs.androidwifiadb.action.AndroidWiFiADBAction$1.run(AndroidWiFiADBAction.java:52)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:695)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by pedrovgs** [comment]
@mnl-assasin can you provide us the steps to reproduce, the version of IntelliJ/AndroidStudio you are using, the version of the plugin you've installed, the device you've connected, etc?

**Comment by mnleano** [comment]
Hi sir, 
I got it from here: 
https://plugins.jetbrains.com/plugin/7983

But after doing some research with other bugs, I find working thou I got other problem maybe you can help me.

I got an error of 
adb command not found. 

I tried to add these to my ~/.profile and ~/.bash_profile

export PATH=Users/mykelneds/Library/Android/sdk/tools:$PATH
export PATH=Users/mykelneds/Library/Android/sdk/platform-tools:$PATH

**Comment by mnleano** [comment]
so I get back to 
String inex out of bounds after i fix adb not found -_-

https://drive.google.com/file/d/0B9xkpTnF9BXjSk9VeU92MUt5M1E/view?usp=sharing

I got the plugin from the link above.

**Comment by mnleano** [comment]
https://plugins.jetbrains.com/plugin/7983

I tried it again. :( still StringOutOfBounds

**Comment by pedrovgs** [comment]
@mnl-assasin  Which plugin version are you using? The ANDROID_HOME variable is not needed anymore if you install the plugin version 1.2.

**Comment by pedrovgs** [comment]
Already fixed in version 2.0
